// Sign up constants
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

// Login PASSWORD
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// Forgot Password
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

// Logout
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";

// Dashboard
export const DASHBOARD_REQUEST = "DASHBOARD_REQUEST";
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";
export const DASHBOARD_FAILURE = "DASHBOARD_FAILURE";

export const DASHBOARD_Q_AND_A_REQUEST = "DASHBOARD_Q_AND_A_REQUEST";
export const DASHBOARD_Q_AND_A_SUCCESS = "DASHBOARD_Q_AND_A_SUCCESS";
export const DASHBOARD_Q_AND_A_FAILURE = "DASHBOARD_Q_AND_A_FAILURE";

export const DASHBOARD_CLINICAL_NOTES_REQUEST = "DASHBOARD_CLINICAL_NOTES_REQUEST";
export const DASHBOARD_CLINICAL_NOTES_SUCCESS = "DASHBOARD_CLINICAL_NOTES_SUCCESS";
export const DASHBOARD_CLINICAL_NOTES_FAILURE = "DASHBOARD_CLINICAL_NOTES_FAILURE";

export const DASHBOARD_TIMELINE_REQUEST = "DASHBOARD_TIMELINE_REQUEST";
export const DASHBOARD_TIMELINE_SUCCESS = "DASHBOARD_TIMELINE_SUCCESS";
export const DASHBOARD_TIMELINE_FAILURE = "DASHBOARD_TIMELINE_FAILURE";

export const DASHBOARD_TAG_FEED_REQUEST = "DASHBOARD_TAG_FEED_REQUEST";
export const DASHBOARD_TAG_FEED_SUCCESS = "DASHBOARD_TAG_FEED_SUCCESS";
export const DASHBOARD_TAG_FEED_FAILURE = "DASHBOARD_TAG_FEED_FAILURE";

export const DASHBOARD_SELECTED_TAG_REQUEST = "DASHBOARD_SELECTED_TAG_REQUEST";
export const DASHBOARD_SELECTED_TAG_SUCCESS = "DASHBOARD_SELECTED_TAG_SUCCESS";
export const DASHBOARD_SELECTED_TAG_FAILURE = "DASHBOARD_SELECTED_TAG_FAILURE";

export const DASHBOARD_FOLLOW_UNFOLLOW_REQUEST = "DASHBOARD_FOLLOW_UNFOLLOW_REQUEST";
export const DASHBOARD_FOLLOW_UNFOLLOW_SUCCESS = "DASHBOARD_FOLLOW_UNFOLLOW_SUCCESS";
export const DASHBOARD_FOLLOW_UNFOLLOW_FAILURE = "DASHBOARD_FOLLOW_UNFOLLOW_FAILURE";

export const DASHBOARD_QUESTION_DETAIL_REQUEST = "DASHBOARD_QUESTION_DETAIL_REQUEST";
export const DASHBOARD_QUESTION_DETAIL_SUCCESS = "DASHBOARD_QUESTION_DETAIL_SUCCESS";
export const DASHBOARD_QUESTION_DETAIL_FAILURE = "DASHBOARD_QUESTION_DETAIL_FAILURE";

export const DASHBOARD_VET_NOTE_DETAIL_REQUEST = "DASHBOARD_VET_NOTE_DETAIL_REQUEST";
export const DASHBOARD_VET_NOTE_DETAIL_SUCCESS = "DASHBOARD_VET_NOTE_DETAIL_SUCCESS";
export const DASHBOARD_VET_NOTE_DETAIL_FAILURE = "DASHBOARD_VET_NOTE_DETAIL_FAILURE";

export const ADD_COMMENTS_REQUEST = "ADD_COMMENTS_REQUEST";
export const ADD_COMMENTS_SUCCESS = "ADD_COMMENTS_SUCCESS";
export const ADD_COMMENTS_FAILURE = "ADD_COMMENTS_FAILURE";

// Questions
export const QUESTION_REQUEST = "QUESTION_REQUEST";
export const QUESTION_SUCCESS = "QUESTION_SUCCESS";
export const QUESTION_FAILURE = "QUESTION_FAILURE";

// Category 
export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAILURE = "CATEGORY_FAILURE";

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

// My profile 
export const MY_PROFILE_REQUEST = "MY_PROFILE_REQUEST";
export const MY_PROFILE_SUCCESS = "MY_PROFILE_SUCCESS";
export const MY_PROFILE_FAILURE = "MY_PROFILE_FAILURE";

//Others 
export const FAQ_REQUEST = "FAQ_REQUEST";
export const FAQ_SUCCESS = "FAQ_SUCCESS";
export const FAQ_FAILURE = "FAQ_FAILURE";

export const FAQ_DETAIL_REQUEST = "FAQ_DETAIL_REQUEST";
export const FAQ_DETAIL_SUCCESS = "FAQ_DETAIL_SUCCESS";
export const FAQ_DETAIL_FAILURE = "FAQ_DETAIL_FAILURE";

export const COLLECTION_REQUEST = "COLLECTION_REQUEST";
export const COLLECTION_SUCCESS = "COLLECTION_SUCCESS";
export const COLLECTION_FAILURE = "COLLECTION_FAILURE";

export const GROUP_QUESTION_REQUEST = "GROUP_QUESTION_REQUEST";
export const GROUP_QUESTION_SUCCESS = "GROUP_QUESTION_SUCCESS";
export const GROUP_QUESTION_FAILURE = "GROUP_QUESTION_FAILURE";

export const HELP_REQUEST = "HELP_REQUEST";
export const HELP_SUCCESS = "HELP_SUCCESS";
export const HELP_FAILURE = "HELP_FAILURE";

export const MY_PAGE_REQUEST = "MY_PAGE_REQUEST";
export const MY_PAGE_SUCCESS = "MY_PAGE_SUCCESS";
export const MY_PAGE_FAILURE = "MY_PAGE_FAILURE";

export const COMMUNITY_SCORE_REQUEST = "COMMUNITY_SCORE_REQUEST";
export const COMMUNITY_SCORE_SUCCESS = "COMMUNITY_SCORE_SUCCESS";
export const COMMUNITY_SCORE_FAILURE = "COMMUNITY_SCORE_FAILURE";

// POST ANSWER 
export const POST_ANSWER_REQUEST = "POST_ANSWER_REQUEST";
export const POST_ANSWER_SUCCESS = "POST_ANSWER_SUCCESS";
export const POST_ANSWER_FAILURE = "POST_ANSWER_FAILURE";

//POST QUESTION
export const POST_QUESTION_REQUEST = "POST_QUESTION_REQUEST";
export const POST_QUESTION_SUCCESS = "POST_QUESTION_SUCCESS";
export const POST_QUESTION_FAILURE = "POST_QUESTION_FAILURE";

export const POST_DRAFT_AS_A_QUESTION_REQUEST = "POST_DRAFT_AS_A_QUESTION_REQUEST";
export const POST_DRAFT_AS_A_QUESTION_SUCCESS = "POST_DRAFT_AS_A_QUESTION_SUCCESS";
export const POST_DRAFT_AS_A_QUESTION_FAILURE = "POST_DRAFT_AS_A_QUESTION_FAILURE";

export const GET_SPECIALITY_REQUEST = "GET_SPECIALITY_REQUEST";
export const GET_SPECIALITY_SUCCESS = "GET_SPECIALITY_SUCCESS";
export const GET_SPECIALITY_FAILURE = "GET_SPECIALITY_FAILURE";

export const GET_ANIMAL_SPECIES_REQUEST = "GET_ANIMAL_SPECIES_REQUEST";
export const GET_ANIMAL_SPECIES_SUCCESS = "GET_ANIMAL_SPECIES_SUCCESS";
export const GET_ANIMAL_SPECIES_FAILURE = "GET_ANIMAL_SPECIES_FAILURE";

export const GET_DATA_TO_POST_QUESTION_REQUEST = "GET_DATA_TO_POST_QUESTION_REQUEST";
export const GET_DATA_TO_POST_QUESTION_SUCCESS = "GET_DATA_TO_POST_QUESTION_SUCCESS";
export const GET_DATA_TO_POST_QUESTION_FAILURE = "GET_DATA_TO_POST_QUESTION_FAILURE";

