const signupConstants = {
  TITLE: "Register with iVet teacher",
  ACCOUNT_TYPE: "Account type",
  NAME:'Name',
  LAST_NAME:'Last',
  LAST_KANA_NAME:'Last Kana',
  FIRST_NAME:'First',
  FIRST_KANA_NAME:'First_kana', 
  EMAIL_ADDRESS: "Email address",
  PASSWORD: "Password",
  SIGN_UP:"SignUp",
  PHYSICIAN_QUALIFICATION: "Physician national qualification",
  CERTIFICATE_DESC: "Certificate with face photo for identity verification",
  LICENCE_PASSPORT:'(License/Passport etc.)',
  ROBOT_DESC: "I am not a robot",
  RECAPTCHA: "reCAPTCHA",
  PRIVACY_AND_TERMS_OF_USE: "Privacy & Terms of Use",
  BOTTOM_CONTINUE_TEXT: "By continuing the usage rules and privacy rules of",
  BOTTOM_APP_NAME_TEXT:"iVet",
  IT_IS_CONSIDERED: "It is considered that you have agreed",
  VETERINARIAN: "Veterinary",
    VETENARY_STUDENT:"Vetenary Student",
    ANIMAL_HOSPITAL:"Animal Hospital",
    PROCEED_TO_NEXT:"Proceed to the next",
    CLOSE: 'Close',
    SELECT_AN_ITEM:'Select an item',
    TERMS_OF_USE:'Terms of Use and',
    PRIVACY_POLICY:'Privacy Policy',
    BOTTOM_BLUE_TEXT:"Terms of Use and Privacy",
    CANCEL:'Cancel',
    CONFIRM: 'Confirm',
    PHYSICIAN_QUALIFICATION_STUDENT:'National veterinary qualification (smartphone photography allowed)',
    PLEASE_TRY_AGAIN:"Please try again",
}

const signupConstants1 = {
  TITLE: "iVet先生に新規登録",
  ACCOUNT_TYPE: "アカウント タイプ",
  NAME:'氏名',
  LAST_NAME:'姓',
  KANA_NAME:'カナ',
  LAST_KANA_NAME:'セイ',
  FIRST_NAME:'名',
  FIRST_KANA_NAME:'メイ', 
  EMAIL_ADDRESS: "メール アドレス",
  PASSWORD: "パスワード",
  PHYSICIAN_QUALIFICATION_STUDENT: "獣医師国家資格（スマホ撮影可)",
  STUDENT_ID_DESC: "獣医大学 学生証",
  CERTIFICATE_DESC: "本人確認用顔写真付証明書", 
  CERTIFICATE_DESC_2:"(免許/パスポート等)",
  ROBOT_DESC: "私はロボットではあり",
  RECAPTCHA: "reCAPTCHA",
  PRIVACY_AND_TERMS_OF_USE: "プライバシー - 利用規約",
  BOTTOM_CONTINUE_TEXT: "続行する事で、iVet先生の",
  BOTTOM_BLUE_TEXT:"利用規定とプライバシー規定",
  BOTTOM_LINE2:"に",
  TERMS_OF_USE:'利用規定と',
  PRIVACY_POLICY:'個人情報保護方針',
  BOTTOM_APP_NAME_TEXT:"利用規定とプライバシー規定に",
  LICENCE_PASSPORT:" ",
  IT_IS_CONSIDERED: "同意したものとみなされます",
  VETERINARIAN: "獣医師",
    VETENARY_STUDENT:"獣医学生",
    ANIMAL_HOSPITAL:"Animal Hospital",
    PROCEED_TO_NEXT:"次へ進む",
    CLOSE: '閉じる',
    SELECT_AN_ITEM:'会員タイプを選択してください',
    CANCEL:'キャンセル',
    CONFIRM:'確認する',
    PLEASE_TRY_AGAIN:"もう一度お試しください",
}
export default signupConstants;